[project]
name = "fastapi-yelp-postgres"
version = "0.1.0"
description = "fast api for yelp data stored in postgres"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "boto3>=1.42.21",
    "dbt-core>=1.7.0",
    "dbt-postgres>=1.7.0",
    "fastapi[all]>=0.119.1",
    "mangum>=0.20.0",
    "pip>=25.3",
    "psycopg2>=2.9.11",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.12.3",
    "pydantic-settings>=2.11.0",
    "python-multipart>=0.0.20",
    "sqlalchemy>=2.0.44",
    "uvicorn[standard]>=0.38.0",
]

[project.optional-dependencies]
test = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "httpx>=0.24.0",
]
