service: yelp-app-serverless

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: prod
  environment:
    DATABASE_HOST: ${env:DATABASE_HOST}
    DATABASE_PORT: ${env:DATABASE_PORT, '5432'}
    DATABASE_NAME: ${env:DATABASE_NAME}
    DATABASE_USER: ${env:DATABASE_USER}
    DATABASE_PASSWORD: ${env:DATABASE_PASSWORD}
  
  # vpc:
  #   securityGroupIds:
  #     - sg-xxxxx  # Your database security group
  #   subnetIds:
  #     - subnet-xxxxx  # Your private subnet 1
  #     - subnet-yyyyy  # Your private subnet 2

functions:
  api:
    handler: src.lambda_handler.handler
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true

custom:
  pythonRequirements:
    dockerizePip: true
    pythonBin: python3.11
